apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: server